//! Precision for C1, C2 and C3, measured **per rule** against ground truth written first
//! (Slices 13b and 13c).
//!
//! Three rules, three tables, **no combined number**. Rows 2a, 9b, 10a and 10b each established
//! that and it is not reopened here: a single "contract precision" figure would let a rule with a
//! hundred easy declarations hide a rule with three hard ones, and the three rules read different
//! files in different languages with different failure modes.
//!
//! The gate is **FP = 0**. Recall is computed and printed and is **not** gated, for the reason rows
//! 2a and 9b give: a recall gate is met by guessing.
//!
//! # What counts as what
//!
//! Ground truth is `fixtures/contracts-npm/ground_truth.json`,
//! `fixtures/contracts-exports/ground_truth.json` and
//! `fixtures/contracts-python/ground_truth.json`. All three are hand-written, all three were
//! written before the resolver existed, and none is produced by running Nerve — a file generated by
//! the thing it grades measures nothing but self-consistency.
//!
//! Declarations are keyed by two things that identify a declaration and that cannot be obtained
//! only by running the code under test. For C1 and C3 that is `(manifest section, dependency key)`;
//! for C2 it is `(importing file, import specifier)`, because the same specifier written in two
//! files is two declarations. [`KeyBy`] is which of the two a document uses, and it is stated in
//! the document rather than inferred.
//!
//! - **TP** — a ground-truth `link` row for which the scan produced a link to the named target with
//!   the named `resolution_method` and the named `form`.
//! - **FP** — any produced link that is not a TP: a link for a row whose verdict is `unresolved` or
//!   `unsupported`, a link for a declaration no ground-truth row mentions, a link to the wrong
//!   target, by the wrong method, or in the wrong form — and a *second* link for a declaration the
//!   oracle says produces one.
//! - **FN** — a ground-truth `link` row with no produced link, **and** every `declined_true_link`
//!   row: a declaration that names a real target through a form outside the enumerated syntax. That
//!   is 10b's `Views.handle` rule — a rule that declines a shape declares the miss rather than
//!   quietly resolving it — and it is why recall is below 1 in all three tables.
//!
//! `unresolved` and `unsupported` rows are not "misses". They are declarations whose correct answer
//! is *no link*, and producing one for them is a false positive rather than a lost recall point.

mod common;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use common::copy_tree;
use nerve_index::contracts::{
    scan_contracts, ContractRule, ContractScan, RecordedLink, ScanOutcome, UnresolvedDeclaration,
    UnsupportedDeclaration,
};
use nerve_index::registry::{add_registry_target, RegistryOutcome};
use serde_json::Value;

/// Which pair of stated facts identifies a declaration in one oracle.
///
/// Two rules cannot share one key. A C1 declaration lives at a `(section, dependency key)` inside a
/// manifest; a C2 declaration lives at an `(importing file, specifier)` inside a repository, and the
/// same specifier in two files is genuinely two declarations. Naming the choice keeps the oracle
/// documents readable on their own terms rather than making one of them lie about what its
/// `section` field holds.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum KeyBy {
    /// C1 and C3: the manifest section and the dependency key.
    SectionAndName,
    /// C2: the importing module's path and the import specifier.
    FileAndSpecifier,
}

impl KeyBy {
    fn of(self, link: &RecordedLink) -> (String, String) {
        self.pair(&link.manifest, &link.section, &link.identity)
    }

    fn of_unresolved(self, row: &UnresolvedDeclaration) -> (String, String) {
        self.pair(&row.manifest, &row.section, &row.identity)
    }

    fn of_unsupported(self, row: &UnsupportedDeclaration) -> (String, String) {
        self.pair(&row.manifest, &row.section, &row.identity)
    }

    fn pair(self, manifest: &str, section: &str, identity: &str) -> (String, String) {
        match self {
            KeyBy::SectionAndName => (section.to_string(), identity.to_string()),
            KeyBy::FileAndSpecifier => (manifest.to_string(), identity.to_string()),
        }
    }
}

/// One target a ground-truth `link` row says must be produced.
///
/// C1 and C3 rows name exactly one; a C2 row may name two, because one specifier that two
/// registered neighbours both claim produces two links and promotes neither.
#[derive(Debug, Clone, PartialEq, Eq)]
struct ExpectedTarget {
    registry_id: String,
    method: String,
    form: String,
}

impl ExpectedTarget {
    /// Every target one declaration row expects, whichever shape the row is written in.
    fn all(row: &Value) -> Vec<ExpectedTarget> {
        let method = row["resolution_method"].as_str().unwrap().to_string();
        match row.get("targets").and_then(Value::as_array) {
            Some(targets) => targets
                .iter()
                .map(|target| ExpectedTarget {
                    registry_id: target["target"].as_str().unwrap().to_string(),
                    method: method.clone(),
                    form: target["form"].as_str().unwrap().to_string(),
                })
                .collect(),
            None => vec![ExpectedTarget {
                registry_id: row["target"].as_str().unwrap().to_string(),
                method,
                form: row["form"].as_str().unwrap().to_string(),
            }],
        }
    }

    fn of(link: &RecordedLink) -> ExpectedTarget {
        ExpectedTarget {
            registry_id: link.registry_id.clone(),
            method: link.resolution_method.as_str().to_string(),
            form: link.form.as_str().to_string(),
        }
    }
}

/// A distinct project id per repository, so no two checkouts share a `repo_id`.
fn project_id(seed: u8) -> String {
    format!("{:032x}", 0xc0000000u64 + u64::from(seed))
}

fn place(base: &Path, fixture: &str, name: &str) -> PathBuf {
    let root = base.join(name);
    copy_tree(
        &common::named_fixture_root(&format!("{fixture}/{name}")),
        &root,
    );
    root
}

fn conn_for(root: &Path) -> nerve_store::Connection {
    nerve_store::open(&nerve_index::config::db_path(root)).unwrap()
}

fn repo_id_of(root: &Path) -> String {
    nerve_store::repository(&conn_for(root))
        .unwrap()
        .unwrap()
        .repo_id
}

fn ground_truth(fixture: &str) -> Value {
    let path = common::named_fixture_root(fixture).join("ground_truth.json");
    serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap()
}

/// One rule's measurement. There is no method that combines two of these, and that is the point.
#[derive(Debug, Default)]
struct PrecisionTable {
    rule: &'static str,
    fixture: &'static str,
    ground_truth_links: usize,
    produced_links: usize,
    true_positives: usize,
    false_positives: Vec<String>,
    false_negatives: Vec<String>,
}

impl PrecisionTable {
    fn precision(&self) -> f64 {
        let denominator = self.true_positives + self.false_positives.len();
        if denominator == 0 {
            1.0
        } else {
            self.true_positives as f64 / denominator as f64
        }
    }

    fn recall(&self) -> f64 {
        let denominator = self.true_positives + self.false_negatives.len();
        if denominator == 0 {
            1.0
        } else {
            self.true_positives as f64 / denominator as f64
        }
    }

    /// Print one rule's table. One rule per call, and never two rules in one row.
    fn report(&self) {
        println!("\n  contract precision — {} ({})", self.rule, self.fixture);
        println!("  {:<28} {}", "ground-truth links", self.ground_truth_links);
        println!("  {:<28} {}", "produced links", self.produced_links);
        println!("  {:<28} {}", "true positives", self.true_positives);
        println!(
            "  {:<28} {}",
            "false positives (gated)",
            self.false_positives.len()
        );
        println!(
            "  {:<28} {}",
            "false negatives (reported)",
            self.false_negatives.len()
        );
        println!("  {:<28} {:.3}", "precision", self.precision());
        println!("  {:<28} {:.3}", "recall (not gated)", self.recall());
        for row in &self.false_positives {
            println!("    FP {row}");
        }
        for row in &self.false_negatives {
            println!("    FN {row}");
        }
    }
}

/// Grade one scan against one ground-truth document. One rule, one table.
fn measure(
    rule: &'static str,
    fixture: &'static str,
    truth: &Value,
    scan: &ContractScan,
    contract_rule: ContractRule,
    key_by: KeyBy,
) -> PrecisionTable {
    let declarations = truth["declarations"].as_array().unwrap();

    // Ground truth, keyed by the two things that identify a declaration.
    let mut expected_links: BTreeMap<(String, String), Vec<ExpectedTarget>> = BTreeMap::new();
    let mut expected_unresolved: BTreeMap<(String, String), &str> = BTreeMap::new();
    let mut expected_unsupported: BTreeMap<(String, String), &str> = BTreeMap::new();
    let mut declined_true_links: BTreeMap<(String, String), &str> = BTreeMap::new();
    let mut expected_link_rows = 0usize;
    for row in declarations {
        let key = (
            row["section"].as_str().unwrap().to_string(),
            row["name"].as_str().unwrap().to_string(),
        );
        match row["verdict"].as_str().unwrap() {
            "link" => {
                let targets = ExpectedTarget::all(row);
                expected_link_rows += targets.len();
                expected_links.insert(key, targets);
            }
            "unresolved" => {
                expected_unresolved.insert(key, row["reason"].as_str().unwrap());
            }
            "unsupported" => {
                expected_unsupported.insert(key, row["form"].as_str().unwrap());
            }
            "declined_true_link" => {
                // Both, and deliberately: the declaration must be *recorded* with its form named,
                // and it must be *counted* as a miss. Recording without counting would hide the
                // cost of the enumerated syntax behind a perfect recall figure.
                expected_unsupported.insert(key.clone(), row["form"].as_str().unwrap());
                declined_true_links.insert(key, row["would_be_target"].as_str().unwrap());
            }
            other => panic!("unknown verdict {other}"),
        }
    }

    let mut table = PrecisionTable {
        rule,
        fixture,
        ground_truth_links: expected_link_rows + declined_true_links.len(),
        ..PrecisionTable::default()
    };

    // Every expectation is *consumed* as it is matched, so a declaration the oracle says produces
    // one link and that produced two contributes a false positive rather than a second true one.
    let mut outstanding = expected_links.clone();
    for link in scan.links_of(contract_rule) {
        table.produced_links += 1;
        let key = key_by.of(link);
        let produced = ExpectedTarget::of(link);
        let matched = outstanding
            .get_mut(&key)
            .and_then(|targets| targets.iter().position(|target| *target == produced));
        match (matched, expected_links.get(&key)) {
            (Some(index), _) => {
                table.true_positives += 1;
                outstanding.get_mut(&key).unwrap().remove(index);
            }
            (None, Some(expected)) => table.false_positives.push(format!(
                "{}/{} resolved to {} by {} as {} — ground truth expects {expected:?}",
                key.0, key.1, produced.registry_id, produced.method, produced.form
            )),
            (None, None) => table.false_positives.push(format!(
                "{}/{} produced a link to {} and ground truth says it must produce none",
                key.0, key.1, produced.registry_id
            )),
        }
    }
    for (key, targets) in &outstanding {
        for target in targets {
            table.false_negatives.push(format!(
                "{}/{} produced no link to {} as {}",
                key.0, key.1, target.registry_id, target.form
            ));
        }
    }
    for (key, would_be) in &declined_true_links {
        assert!(
            !scan
                .links_of(contract_rule)
                .any(|link| key_by.of(link) == *key),
            "{}/{} produced a link, and the oracle says this form is declined. That is not a false \
             positive — the target is right — but the oracle is now out of date and must be \
             updated deliberately rather than by a passing test.",
            key.0,
            key.1
        );
        table.false_negatives.push(format!(
            "{}/{} names {would_be} through a declaration outside the enumerated syntax, and is \
             declined",
            key.0, key.1
        ));
    }

    // The other two verdicts are asserted rather than scored: their correct answer is *no link*, so
    // they contribute to precision only by their absence from the produced set, which is already
    // counted above. What is asserted here is that each was reported **with its reason or form
    // named**, which is §9.1's tally and the thing a silent drop would fail.
    for (key, reason) in &expected_unresolved {
        let found = scan
            .unresolved_of(contract_rule)
            .find(|row| key_by.of_unresolved(row) == *key)
            .unwrap_or_else(|| panic!("{}/{} was not reported as unresolved", key.0, key.1));
        assert_eq!(
            found.reason.as_str(),
            *reason,
            "{}/{} was unresolved for the wrong reason",
            key.0,
            key.1
        );
    }
    for (key, form) in &expected_unsupported {
        let found = scan
            .unsupported_of(contract_rule)
            .find(|row| key_by.of_unsupported(row) == *key)
            .unwrap_or_else(|| {
                panic!(
                    "{}/{} was silently dropped rather than recorded as unsupported",
                    key.0, key.1
                )
            });
        assert_eq!(
            found.form.as_str(),
            *form,
            "{}/{} was declined under the wrong form",
            key.0,
            key.1
        );
    }

    // Nothing was reported that ground truth does not know about, in either direction.
    assert_eq!(
        scan.unresolved_of(contract_rule).count(),
        expected_unresolved.len(),
        "the scan reported an unresolved declaration ground truth does not list"
    );
    assert_eq!(
        scan.unsupported_of(contract_rule).count(),
        expected_unsupported.len(),
        "the scan reported an unsupported declaration ground truth does not list"
    );

    table
}

fn scan_of(root: &Path) -> ContractScan {
    let conn = conn_for(root);
    let repo_id = repo_id_of(root);
    match scan_contracts(&conn, &repo_id, root).unwrap() {
        ScanOutcome::Done(scan) => *scan,
        ScanOutcome::Refused(reason) => panic!("the scan refused: {reason}"),
    }
}

/// Register each neighbour under **its own directory name**, so ground truth's `target` is the
/// registry id and no mapping table sits between the oracle and the answer.
fn register(source: &Path, target: &Path) {
    let conn = conn_for(source);
    let repo_id = repo_id_of(source);
    let id = target.file_name().unwrap().to_string_lossy().into_owned();
    match add_registry_target(&conn, &repo_id, target, Some(&id), None).unwrap() {
        RegistryOutcome::Done(_) => {}
        RegistryOutcome::Refused(reason) => panic!("{id} was refused: {reason}"),
    }
}

/// **C1's table.** Its own fixture, its own ground truth, its own gate.
#[test]
fn c1_npm_local_dependency_precision() {
    let dir = tempfile::tempdir().unwrap();
    let app = place(dir.path(), "contracts-npm", "app");
    let core = place(dir.path(), "contracts-npm", "lib-core");
    let extra = place(dir.path(), "contracts-npm", "lib-extra");
    let unregistered = place(dir.path(), "contracts-npm", "unregistered");
    for (root, seed) in [(&app, 1), (&core, 2), (&extra, 3), (&unregistered, 4)] {
        nerve_index::init_with_project_id(root, Some(&project_id(seed))).unwrap();
        nerve_index::index_repository(root).unwrap();
    }
    register(&app, &core);
    register(&app, &extra);

    let truth = ground_truth("contracts-npm");
    let scan = scan_of(&app);
    let table = measure(
        "C1 npm_local_dependency",
        "contracts-npm",
        &truth,
        &scan,
        ContractRule::NpmLocalDependency,
        KeyBy::SectionAndName,
    );
    table.report();

    // The tally §9.1 asks for, against the hand-written totals.
    let totals = &truth["totals"];
    assert_eq!(
        scan.declarations,
        totals["declarations"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.links.len(),
        totals["expected_links"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unresolved.len(),
        totals["expected_unresolved"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unsupported.len(),
        totals["expected_unsupported"].as_u64().unwrap() as usize
    );

    // The gate.
    assert_eq!(
        table.false_positives.len(),
        totals["expected_false_positives"].as_u64().unwrap() as usize,
        "false positives: {:?}",
        table.false_positives
    );
    assert_eq!(table.false_positives.len(), 0, "the gate is FP = 0");
    // Recall is reported, not gated — but a ground truth that expects none must not have any, or
    // the published number would be describing a different fixture.
    assert_eq!(
        table.false_negatives.len(),
        totals["expected_false_negatives"].as_u64().unwrap() as usize,
        "false negatives: {:?}",
        table.false_negatives
    );

    // Anti-vacuity: a table over zero links would pass every assertion above.
    assert!(table.true_positives >= 5, "{table:?}");
}

/// **C3's table.** Separate fixture, separate ground truth, separate gate. Never summed with C1's.
#[test]
fn c3_python_path_dependency_precision() {
    let dir = tempfile::tempdir().unwrap();
    let service = place(dir.path(), "contracts-python", "service");
    let core = place(dir.path(), "contracts-python", "pkg-core");
    let extra = place(dir.path(), "contracts-python", "pkg-extra");
    let unregistered = place(dir.path(), "contracts-python", "unregistered");

    let manifest = service.join("pyproject.toml");
    let template = std::fs::read_to_string(&manifest).unwrap();
    std::fs::write(
        &manifest,
        template.replace(
            "{{PKG_CORE_PATH}}",
            &core.canonicalize().unwrap().to_string_lossy(),
        ),
    )
    .unwrap();

    for (root, seed) in [
        (&service, 11),
        (&core, 12),
        (&extra, 13),
        (&unregistered, 14),
    ] {
        nerve_index::init_with_project_id(root, Some(&project_id(seed))).unwrap();
        nerve_index::index_repository(root).unwrap();
    }
    register(&service, &core);
    register(&service, &extra);

    let truth = ground_truth("contracts-python");
    let scan = scan_of(&service);
    let table = measure(
        "C3 python_path_dependency",
        "contracts-python",
        &truth,
        &scan,
        ContractRule::PythonPathDependency,
        KeyBy::SectionAndName,
    );
    table.report();

    let totals = &truth["totals"];
    assert_eq!(
        scan.declarations,
        totals["declarations"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.links.len(),
        totals["expected_links"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unresolved.len(),
        totals["expected_unresolved"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unsupported.len(),
        totals["expected_unsupported"].as_u64().unwrap() as usize
    );

    assert_eq!(
        table.false_positives.len(),
        totals["expected_false_positives"].as_u64().unwrap() as usize,
        "false positives: {:?}",
        table.false_positives
    );
    assert_eq!(table.false_positives.len(), 0, "the gate is FP = 0");
    assert_eq!(
        table.false_negatives.len(),
        totals["expected_false_negatives"].as_u64().unwrap() as usize,
        "false negatives: {:?}",
        table.false_negatives
    );
    assert!(table.true_positives >= 5, "{table:?}");
}

/// **C2's table.** Its own fixture, its own ground truth, its own gate. Never summed with either
/// of the other two.
///
/// This is the one rule in row 13 that reaches a file entity inside the target, so the table has
/// two anti-vacuity floors rather than one: enough true positives that the numbers describe
/// something, and at least one link that actually carries a foreign `target_entity_id`. A C2 table
/// full of path-only links would satisfy every count above and prove nothing about the thing the
/// rule exists to do.
#[test]
fn c2_npm_export_resolution_precision() {
    let dir = tempfile::tempdir().unwrap();
    let host = place(dir.path(), "contracts-exports", "host");
    let neighbours: Vec<PathBuf> = [
        "pkg-map",
        "pkg-string",
        "pkg-legacy",
        "twin-a",
        "twin-b",
        "pkg-unregistered",
    ]
    .iter()
    .map(|name| place(dir.path(), "contracts-exports", name))
    .collect();

    nerve_index::init_with_project_id(&host, Some(&project_id(21))).unwrap();
    nerve_index::index_repository(&host).unwrap();
    for (offset, root) in neighbours.iter().enumerate() {
        nerve_index::init_with_project_id(root, Some(&project_id(22 + offset as u8))).unwrap();
        nerve_index::index_repository(root).unwrap();
    }
    // `pkg-unregistered` is deliberately left out, and it is the last of the six.
    for root in &neighbours[..5] {
        register(&host, root);
    }

    let truth = ground_truth("contracts-exports");
    let scan = scan_of(&host);
    let table = measure(
        "C2 npm_export_resolution",
        "contracts-exports",
        &truth,
        &scan,
        ContractRule::NpmExportResolution,
        KeyBy::FileAndSpecifier,
    );
    table.report();

    // The tally §9.1 asks for, against the hand-written totals — **per rule**, because this scan
    // also produced C1 links from the same manifest and adding the two would be the combined
    // number three rows have now refused.
    let totals = &truth["totals"];
    let c2_links = scan.links_of(ContractRule::NpmExportResolution).count();
    assert_eq!(
        c2_links,
        totals["expected_links"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unresolved_of(ContractRule::NpmExportResolution)
            .count(),
        totals["expected_unresolved"].as_u64().unwrap() as usize
    );
    assert_eq!(
        scan.unsupported_of(ContractRule::NpmExportResolution)
            .count(),
        totals["expected_unsupported"].as_u64().unwrap() as usize
    );

    // The gate.
    assert_eq!(
        table.false_positives.len(),
        totals["expected_false_positives"].as_u64().unwrap() as usize,
        "false positives: {:?}",
        table.false_positives
    );
    assert_eq!(table.false_positives.len(), 0, "the gate is FP = 0");
    assert_eq!(
        table.false_negatives.len(),
        totals["expected_false_negatives"].as_u64().unwrap() as usize,
        "false negatives: {:?}",
        table.false_negatives
    );

    // Anti-vacuity, both halves.
    assert!(table.true_positives >= 5, "{table:?}");
    let with_entity = scan
        .links_of(ContractRule::NpmExportResolution)
        .filter(|link| link.target_entity_id.is_some())
        .count();
    assert!(
        with_entity >= 5,
        "only {with_entity} C2 links name an entity in the neighbour; the rule exists to reach one"
    );
    assert_eq!(
        c2_links - with_entity,
        totals["links_with_no_target_entity"].as_u64().unwrap() as usize,
        "a link with a path and no entity is `target_partially_indexed`, and the oracle counts them"
    );
}

/// **No combined number exists.** Asserted over the ground truth documents themselves.
///
/// The three tables above are separate values with separate gates and there is no method on
/// [`PrecisionTable`] that adds one to another — but the durable risk is a *document* growing a
/// summary row, so the oracles are scanned for one. Each file must declare exactly one rule, and
/// none may carry a total that spans another.
#[test]
fn neither_ground_truth_document_carries_a_combined_number() {
    let mut rules = BTreeSet::new();
    for fixture in ["contracts-npm", "contracts-exports", "contracts-python"] {
        let truth = ground_truth(fixture);
        let rule = truth["rule"].as_str().unwrap().to_string();
        assert!(
            rules.insert(rule.clone()),
            "{fixture} claims a rule another oracle already claims"
        );
        assert!(
            truth["note"]
                .as_array()
                .unwrap()
                .iter()
                .any(|line| line.as_str().unwrap().contains("NEVER SUMMED")),
            "{fixture} no longer states that its table is not summed"
        );
        let totals = truth["totals"].as_object().unwrap();
        for key in totals.keys() {
            assert!(
                !key.contains("combined") && !key.contains("overall") && !key.contains("total_all"),
                "{fixture} grew a combined total: {key}"
            );
        }
    }
    assert_eq!(rules.len(), 3, "the three oracles are not three rules");
}
