//! Nerve accepts what the reference tracer actually emitted — hermetically, on every `cargo test`.
//!
//! `fixtures/trace-basic`'s four artifacts are hand-written, and
//! `docs/plans/slice-11a-trace-ingestion.md` §3 records why that is the right choice rather than a
//! shortcut: a real tracer cannot emit a traversal path, malformed UTF-8 or a prompt-injection
//! payload, so generating the fixtures would make the security half of Slice 11a untestable.
//!
//! But the converse is also true, and it is what this file is for: a **hand-written** artifact cannot
//! demonstrate that a real producer exists, agrees with the reader, and gets the attribution right.
//! `fixtures/trace-python-e2e/produced.jsonl` is the canonicalised output of a genuine pytest run
//! under `tracers/python/nerve_trace`, regenerated and diffed by `scripts/trace_python_e2e.sh` —
//! which needs pytest and therefore cannot run here. Committing its output is what makes the
//! *ingestion* of a genuinely-produced artifact hermetic, which is the property that matters.
//!
//! This parses; it does not import. `parse_trace` takes `&[u8]` and returns a value, so no database,
//! no repository and no index are involved, and the whole file is a pure function of a committed
//! fixture. What it therefore cannot show is the *binding*, which needs an index to compare against.
//! `scripts/trace_python_e2e.sh` covers that in its non-hermetic layer: it makes the traced copy a git
//! repository, indexes it, imports the **raw** artifact, and asserts `binding: bound` with zero
//! refusals. Measured there, not here.
//!
//! **`git_commit` is forty zeros, and that is a canonicalisation rather than a fact.** A real commit
//! id changes every run — a commit object carries its own timestamp — so the diff in that script
//! replaces it. Forty zeros rather than a `__TOKEN__` because `git_commit` is the one canonicalised
//! field whose *shape* the reader validates: `optional_hex_field` requires exactly 40 lowercase hex
//! characters, and a token is refused as `header-invalid`, rejecting the artifact whole. A placeholder
//! has to satisfy its own field's contract or the fixture stops being an artifact. Measured: a
//! `__GIT_COMMIT__` token failed five of the six tests in this file.
//!
//! `content_merkle` is null in every artifact this producer writes, and that is a real fact rather
//! than a canonicalisation: computing Nerve's own digest would mean reimplementing an internal of the
//! product this package is deliberately not part of.
//!
//! So the sentinel commit means an *import of this fixture* would report `stale` — it names a tree
//! that is not yours. That is the correct answer for a canonicalised artifact, and it is why the
//! binding is asserted in the script over the raw output instead.

use nerve_index::trace::{form, limitation, parse_trace, CompletionState, SourceMapState};

fn artifact() -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/trace-python-e2e/produced.jsonl");
    std::fs::read(&path).unwrap_or_else(|err| {
        panic!(
            "{} must be readable ({err}). It is regenerated by scripts/trace_python_e2e.sh.",
            path.display()
        )
    })
}

/// Every located edge as `(caller_file, caller_line, callee_file, callee_line, count)`.
fn sites(bytes: &[u8]) -> Vec<(String, u64, String, u64, u64)> {
    parse_trace(bytes)
        .records
        .into_iter()
        .map(|record| {
            (
                record.caller_file,
                record.caller_line,
                record.callee_file,
                record.callee_line,
                record.count,
            )
        })
        .collect()
}

#[test]
fn a_genuinely_produced_artifact_parses_with_no_refusals_at_all() {
    let parsed = parse_trace(&artifact());
    assert!(
        parsed.counters.refused.is_empty(),
        "the reference tracer emitted something Nerve refuses: {:?}. A producer in this repository \
         has no excuse for a refusal — every bound it must respect is mirrored in \
         tracers/python/nerve_trace/record.py and asserted in no_tracer_reference.rs.",
        parsed.counters.refused
    );
    assert_eq!(parsed.counters.refused_total(), 0);
    assert!(
        parsed.counters.limitations.is_empty(),
        "this run had no unobservable frames to admit to: {:?}",
        parsed.counters.limitations
    );
    assert_eq!(parsed.records.len(), parsed.records_in_artifact);
}

#[test]
fn the_header_is_the_one_the_producer_documents() {
    let parsed = parse_trace(&artifact());
    let header = parsed
        .header
        .expect("the artifact must have a usable header");
    assert_eq!(header.producer, "nerve-trace-python");
    assert_eq!(header.test_framework, "pytest");
    assert_eq!(header.runtime, "cpython");
    assert_eq!(header.repository_root_name, "trace-basic");
    assert_eq!(header.completion_state, CompletionState::Complete);
    assert_eq!(header.source_map_state, SourceMapState::None);
    assert!(
        header.completed_at.is_some(),
        "a complete run must say when, and the producer refuses to claim otherwise"
    );
    assert!(header.partial_reason.is_none());

    // `content_merkle` is null on purpose — computing Nerve's digest is not a producer's job.
    assert!(header.content_merkle.is_none());

    // `git_commit` is the canonicaliser's sentinel, and it is asserted **exactly** rather than merely
    // being allowed to be something. A canonicalised field that drifted to a real commit id would make
    // this fixture unreproducible, and one that drifted to a token would make the whole artifact
    // `header-invalid`; pinning the value catches both. The module documentation says why forty zeros.
    assert_eq!(
        header.git_commit.as_deref(),
        Some("0000000000000000000000000000000000000000"),
        "the canonicalised sentinel commit must survive verbatim; a real id here means \
         scripts/trace_python_e2e.sh stopped canonicalising and the fixture will rot"
    );

    for declared in &header.producer_limitations {
        assert!(
            limitation::is_known(declared),
            "the producer declared `{declared}`, which is outside the reader's closed vocabulary; \
             it would be counted as `{}` and dropped",
            form::LIMITATION_UNKNOWN
        );
    }
    for expected in [
        limitation::NATIVE_FRAMES,
        limitation::THREADS,
        limitation::ASYNC_CONTINUATIONS,
        limitation::MULTIPROCESSING_CHILDREN,
        limitation::GENERATED_CODE,
    ] {
        assert!(
            header.producer_limitations.iter().any(|d| d == expected),
            "the producer stopped declaring `{expected}`, which it cannot observe"
        );
    }
    for overstated in [
        limitation::DYNAMIC_IMPORTS,
        limitation::SAMPLING_GAP,
        limitation::PROFILER_CONTENTION,
    ] {
        assert!(
            !header.producer_limitations.iter().any(|d| d == overstated),
            "the producer declared `{overstated}`, which it does not actually suffer from; \
             overstating blindness is as misleading as understating it"
        );
    }
}

/// The property the whole slice exists to keep, measured on a real run rather than a written one.
///
/// `fixtures/trace-basic/tests/test_parse.py::test_basic` calls `parse`, which calls `tokenize` and
/// `classify`. The produced artifact must attribute those two to **`src/parse.py`**, and must never
/// name `tests/test_parse.py` as the caller of anything in `src/lex.py`.
#[test]
fn a_real_run_attributes_a_nested_call_to_its_real_caller_and_never_to_the_test() {
    let bytes = artifact();
    let sites = sites(&bytes);
    assert!(
        !sites.is_empty(),
        "no records, so everything below passes vacuously"
    );

    assert!(
        sites
            .iter()
            .any(|s| s.0 == "src/parse.py" && s.1 == 10 && s.2 == "src/lex.py" && s.3 == 4),
        "the depth-2 call to `tokenize` must be attributed to `parse`: {sites:?}"
    );
    assert!(
        sites
            .iter()
            .any(|s| s.0 == "src/parse.py" && s.1 == 11 && s.2 == "src/lex.py" && s.3 == 9),
        "the depth-2 call to `classify` must be attributed to `parse`: {sites:?}"
    );
    // Depth 3: `Parser.parse_all` reaches `parse`, which reaches `tokenize`.
    assert!(
        sites
            .iter()
            .any(|s| s.0 == "src/parse.py" && s.1 == 26 && s.2 == "src/parse.py" && s.3 == 8),
        "`parse_all` must be the caller of `parse`: {sites:?}"
    );

    let callers_into_lex: Vec<&String> = sites
        .iter()
        .filter(|s| s.2 == "src/lex.py")
        .map(|s| &s.0)
        .collect();
    assert!(!callers_into_lex.is_empty());
    for caller in callers_into_lex {
        assert_eq!(
            caller, "src/parse.py",
            "a test function became the source of a call it never made: {sites:?}"
        );
    }
}

/// `count` accumulates. `parse` classifies two tokens from `"a 1"`, so one record says so.
#[test]
fn a_repeated_call_is_one_record_with_a_count() {
    let all = sites(&artifact());
    let classify: Vec<&(String, u64, String, u64, u64)> = all
        .iter()
        .filter(|site| site.0 == "src/parse.py" && site.1 == 11 && site.3 == 9)
        .collect();
    assert!(
        !classify.is_empty(),
        "the `classify` edge is missing: {all:?}"
    );
    assert!(
        classify.iter().any(|site| site.4 == 2),
        "`parse(\"a 1\")` classifies two tokens, which must be one record with `count: 2` rather \
         than two records — an artifact that listed every call would be unbounded: {classify:?}"
    );

    // One `(test, site)` pair is one record. Two records for one pair would mean the accumulator
    // stopped accumulating, which is the failure `count` exists to prevent.
    let parsed = parse_trace(&artifact());
    let mut keys: Vec<(String, String, u64, String, u64)> = parsed
        .records
        .iter()
        .map(|record| {
            (
                record.test_id.clone(),
                record.caller_file.clone(),
                record.caller_line,
                record.callee_file.clone(),
                record.callee_line,
            )
        })
        .collect();
    let total = keys.len();
    keys.sort();
    keys.dedup();
    assert_eq!(
        keys.len(),
        total,
        "the same call site was recorded twice under one test"
    );
}

#[test]
fn no_path_in_a_produced_artifact_is_absolute_or_escapes_the_root() {
    for site in sites(&artifact()) {
        for path in [site.0, site.2] {
            assert!(
                !path.starts_with('/'),
                "absolute path in the artifact: {path}"
            );
            assert!(
                !path.contains('\\'),
                "backslash spelling in the artifact: {path}"
            );
            assert!(
                !path.split('/').any(|segment| segment == ".."),
                "traversal segment in the artifact: {path}"
            );
        }
    }
}

/// Every test the run executed is named, and nothing else is.
#[test]
fn provenance_names_the_tests_and_the_endpoints_name_the_frames() {
    let parsed = parse_trace(&artifact());
    let mut tests: Vec<String> = parsed.records.iter().map(|r| r.test_id.clone()).collect();
    tests.sort();
    tests.dedup();
    assert_eq!(
        tests,
        vec![
            "tests/test_parse.py::test_basic".to_string(),
            "tests/test_parse.py::test_lazy_import".to_string(),
            "tests/test_parse.py::test_method".to_string(),
            "tests/test_parse.py::test_partial".to_string(),
        ]
    );
    for record in &parsed.records {
        assert!(
            record.worker.is_some(),
            "the producer names the worker it observed the frame on"
        );
        assert!(
            record.async_context.is_none(),
            "this producer tracks no async context and must not invent one"
        );
    }
}
